SDC-16947. Add deployment events reporting to _sdc script
 * _sdc detects if it is running from a deployment install or a deployment rerun
 * if so, it will source a script from SCH to  be able to report events

Change-Id: Id8d44f8941c60f1926518b1a6889b4cb5c436320
Reviewed-on: https://review.streamsets.net/c/datacollector/+/40949
Tested-by: StreamSets CI <streamsets-ci-spam@streamsets.com>
Reviewed-by: Santhosh Kumar <santhosh@streamsets.com>

diff --git a/dist/src/main/libexec/_sdc b/dist/src/main/libexec/_sdc
--- a/dist/src/main/libexec/_sdc
+++ b/dist/src/main/libexec/_sdc
@@ -14,7 +14,6 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
-
 # resolve links - $0 may be a softlink
 PRG="${0}"
 
@@ -39,6 +38,8 @@ PRG="${0}"
 VERBOSE=0
 EXEC=0
 SKIP_ENV_SOURCING=0
+DEPLOYMENT_INSTALL=0
+DEPLOYMENT_RUN=0
 while test $# -gt 0; do
   case "${1}" in
     -verbose)
@@ -51,6 +52,10 @@ while test $# -gt 0; do
       ;;
     -skipenvsourcing)
       SKIP_ENV_SOURCING=1
+      shift
+      ;;
+    -deploymentinstall)
+      DEPLOYMENT_INSTALL=1
       shift
       ;;
     -help)
@@ -87,6 +92,81 @@ SDC_DATA=${SDC_DATA:=${SDC_HOME}/data}
 SDC_LOG=${SDC_LOG:=${SDC_HOME}/log}
 SDC_EXTERNAL_RESOURCES=${SDC_EXTERNAL_RESOURCES:=${SDC_HOME}/externalResources}
 SDC_RESOURCES=${SDC_RESOURCES:=${SDC_EXTERNAL_RESOURCES}/resources}
+
+############################## DEPLOYMENT INTEGRATION
+if [[ ${DEPLOYMENT_INSTALL} -eq 0 ]]; then
+  # not running within a deployment engine install run
+
+  # defining run() and reportEvent() functions for non-deployment runs
+  run() {
+    $@
+    RET=$?
+  }
+  reportEvent() {
+    echo ${1} - ${4}
+  }
+
+  # detect if the engine is configured to run as part of a deployment
+  # we need the SCH URL, deployment ID, deployment token and boostrap deployment scripts to be avail
+  if [[ -f ${SDC_CONF}/dpm-url.txt ]] && [[ -f ${SDC_CONF}/deployment.id ]] && [[ -f ${SDC_CONF}/deployment-token.txt ]]; then
+    DEPLOYMENT_RUN=1
+    SCH_URL_FROM_FILE=$(cat ${SDC_CONF}/dpm-url.txt)
+    ID_FROM_FILE=$(cat ${SDC_CONF}/deployment.id)
+    TOKEN_FROM_FILE=$(cat ${SDC_CONF}/deployment-token.txt)
+    STREAMSETS_DEPLOYMENT_SCH_URL=${STREAMSETS_DEPLOYMENT_SCH_URL:=${SCH_URL_FROM_FILE}}
+    STREAMSETS_DEPLOYMENT_ID=${STREAMSETS_DEPLOYMENT_ID:=${ID_FROM_FILE}}
+    STREAMSETS_DEPLOYMENT_TOKEN=${STREAMSETS_DEPLOYMENT_TOKEN:=${TOKEN_FROM_FILE}}
+  fi
+
+else
+  if [ -z ${STREAMSETS_DEPLOYMENT_SCH_URL} ]; then
+    echo "ERROR - STREAMSETS_DEPLOYMENT_SCH_URL not set"
+    exit 1
+  fi
+  if [ -z ${STREAMSETS_DEPLOYMENT_ID} ]; then
+    echo "ERROR - STREAMSETS_DEPLOYMENT_ID not set"
+    exit 1
+  fi
+  if [ -z ${STREAMSETS_DEPLOYMENT_TOKEN} ]; then
+    echo "ERROR - STREAMSETS_DEPLOYMENT_TOKEN not set"
+    exit 1
+  fi
+  DEPLOYMENT_RUN=1
+fi
+
+if [[ ${DEPLOYMENT_RUN} -eq 1 ]]; then
+    # Runs a command capturing its STDOUT, STDERR and EXIT_CODE in 3 variables: OUT, ERR, RET
+  # This is a temporary version of the function, gets replaced after we source `deployment-tools.sh`
+  run() {
+  # parameters: command parameters....
+    unset t_std t_err t_ret
+    eval "$( "$@" \
+      2> >(t_err=$(cat); typeset -p t_err) \
+      > >(t_std=$(cat); typeset -p t_std); t_ret=$?; typeset -p t_ret )"
+    OUT=$t_std
+    ERR=$t_err
+    RET=$t_ret
+
+    if [[ ${RET} -ne 0 ]]; then
+      echo ""
+      echo "ERROR running  : $@"
+      echo "      exit code: $RET"
+      echo "      std error: $ERR"
+      echo ""
+    fi
+  }
+
+  run curl -s -S -X GET ${STREAMSETS_DEPLOYMENT_SCH_URL}/deployment-tools.sh
+  if [[ ${RET} -eq 0 ]]; then
+    eval "${OUT}" > /dev/null
+    if [[ $? -ne 0 ]]; then
+      echo "Error setting up script tools"
+      exit 1
+    fi
+  fi
+fi
+##############################
+
 
 # Use the percentage rate of available memory for the heap size if SDC_HEAP_SIZE_PERCENTAGE is
 # specified and the calculated size is greater than 512m but limited by ulimit and cgroup. Note that
@@ -176,7 +256,7 @@ fi
 
 if [ -z "$JAVA" ]
 then
-  echo "Can't find java, please set JAVA_HOME pointing to your java installation"
+  reportEvent "ERROR" "STARTUP" "S01" "Can't find java, please set JAVA_HOME pointing to your java installation"
   exit 1
 fi
 
@@ -257,8 +337,9 @@ then
   # And unless unsupported JDK is explicitly enabled, die
   if [[ "${SDC_ALLOW_UNSUPPORTED_JDK}" != "true" ]]
   then
-  echo "ERROR: Please install supported JDK or explicitly allow unsupported JDKs via SDC_ALLOW_UNSUPPORTED_JDK=true"
-    exit 1
+  echo ${MESSAGE}
+  reportEvent "ERROR" "STARTUP" "S02" "Please install supported JDK or explicitly allow unsupported JDKs via SDC_ALLOW_UNSUPPORTED_JDK=true"
+  exit 1
   fi
 fi
 
@@ -317,7 +398,8 @@ cd ${SDC_DIST}
 
 ulimit=`ulimit -n`
 if [[ $ulimit -lt $SDC_FILE_LIMIT ]]; then
-  echo "Configuration of maximum open file limit is too low: $ulimit (expected at least $SDC_FILE_LIMIT). Please consult https://goo.gl/6dmjXd"
+  MESSAGE="Configuration of maximum open file limit is too low: $ulimit (expected at least $SDC_FILE_LIMIT). Please consult https://goo.gl/6dmjXd"
+  reportEvent "ERROR" "STARTUP" "S03" "${MESSAGE}"
   exit 1
 fi
 
@@ -328,8 +410,8 @@ then
 fi
 
 check_curl_and_tar_installed() {
-  if [[ ! -x "$(which curl)" ]] && [[ ! -x "$(which curl)" ]] ; then
-    echo "Curl and Tar commands are needed to run Deployment Bootstrap"
+  if [[ ! -x "$(which curl)" ]] && [[ ! -x "$(which tar)" ]] ; then
+    reportEvent "ERROR" "STARTUP" "S04" "Curl and Tar commands are needed to run Deployment Bootstrap"
     exit -1
   fi
 }
@@ -357,32 +439,39 @@ run_bootstrap() {
     fi
   fi
 
-  if [[ -f ${SDC_CONF}/dpm-url.txt ]]; then
-    SCH_URL_FROM_FILE=$(cat ${SDC_CONF}/dpm-url.txt)
-  fi
-  if [[ -f ${SDC_CONF}/deployment.id ]]; then
-    ID_FROM_FILE=$(cat ${SDC_CONF}/deployment.id)
-  fi
-  if [[ -f ${SDC_CONF}/deployment-token.txt ]]; then
-    TOKEN_FROM_FILE=$(cat ${SDC_CONF}/deployment-token.txt)
-  fi
-  STREAMSETS_DEPLOYMENT_SCH_URL=${STREAMSETS_DEPLOYMENT_SCH_URL:=${SCH_URL_FROM_FILE}}
-  STREAMSETS_DEPLOYMENT_ID=${STREAMSETS_DEPLOYMENT_ID:=${ID_FROM_FILE}}
-  STREAMSETS_DEPLOYMENT_TOKEN=${STREAMSETS_DEPLOYMENT_TOKEN:=${TOKEN_FROM_FILE}}
-
   STREAMSETS_DEPLOYMENT_LIB_EXTRACT_DIR=${STREAMSETS_DEPLOYMENT_LIB_EXTRACT_DIR:=${SDC_DIST}}
 
   if [[ ! -z "${STREAMSETS_DEPLOYMENT_SCH_URL}" ]] && [[ ! -z "${STREAMSETS_DEPLOYMENT_ID}" ]] && [[ ! -z "${STREAMSETS_DEPLOYMENT_TOKEN}" ]]; then
     if [[ ! -d ${STREAMSETS_DEPLOYMENT_LIB_EXTRACT_DIR}/deployment-lib ]]; then
       check_curl_and_tar_installed
-      curl -o ${STREAMSETS_DEPLOYMENT_LIB_EXTRACT_DIR}/bootstrap.tgz -L ${STREAMSETS_DEPLOYMENT_SCH_URL}/engineBootstrap/bootstrap.tgz && \
-      tar xzf ${STREAMSETS_DEPLOYMENT_LIB_EXTRACT_DIR}/bootstrap.tgz --directory ${STREAMSETS_DEPLOYMENT_LIB_EXTRACT_DIR}
-    else
-      echo "Deployment Boostrap already exists"
+
+      run curl -o ${STREAMSETS_DEPLOYMENT_LIB_EXTRACT_DIR}/bootstrap.tgz -L ${STREAMSETS_DEPLOYMENT_SCH_URL}/engineBootstrap/bootstrap.tgz
+      if [[ ${RET} -ne 0 ]]; then
+        MESSAGE="Downloading Bootstrap tarball '${STREAMSETS_DEPLOYMENT_SCH_URL}/engineBootstrap/bootstrap.tgz', ${ERR}"
+        reportEvent "ERROR" "STARTUP" "S06" "${MESSAGE}"
+        exit 1
+      fi
+
+      run tar xzf ${STREAMSETS_DEPLOYMENT_LIB_EXTRACT_DIR}/bootstrap.tgz --directory ${STREAMSETS_DEPLOYMENT_LIB_EXTRACT_DIR}
+      if [[ ${RET} -ne 0 ]]; then
+        MESSAGE="Extracting tarball binary '${STREAMSETS_DEPLOYMENT_LIB_EXTRACT_DIR}/bootstrap.tgz', ${ERR}"
+        reportEvent "ERROR" "STARTUP" "S07" "${MESSAGE}"
+        exit 1
+      fi
     fi
+
+    reportEvent "INFO" "BOOTSTRAP" "B01" "Starting Bootstrap"
+
     STREAMSETS_BOOTSTRAP_MAIN_CLASS="com.streamsets.engine.deployment.bootstrap.DeploymentBootstrapMain"
     STREAMSETS_BOOTSTRAP_JAVA_OPTS="-Dstreamsets.deployment.conf.dir=${SDC_CONF} -Dstreamsets.deployment.data.dir=${SDC_DATA} -Dstreamsets.deployment.stage.lib.dir=${STREAMSETS_LIBRARIES_DIR} ${STREAMSETS_BOOTSTRAP_JAVA_OPTS}"
-    ${JAVA} ${STREAMSETS_BOOTSTRAP_JAVA_OPTS} -classpath "${STREAMSETS_DEPLOYMENT_LIB_EXTRACT_DIR}/deployment-lib/lib/*" ${STREAMSETS_BOOTSTRAP_MAIN_CLASS}
+    run ${JAVA} ${STREAMSETS_BOOTSTRAP_JAVA_OPTS} -classpath "${STREAMSETS_DEPLOYMENT_LIB_EXTRACT_DIR}/deployment-lib/lib/*" ${STREAMSETS_BOOTSTRAP_MAIN_CLASS}
+
+    if [[ ${RET} -ne 0 ]]; then
+      MESSAGE="Bootstrap error, ${ERR}"
+      reportEvent "ERROR" "BOOTSTRAP" "B02" "${MESSAGE}"
+      exit 1
+    fi
+
     if [[ -f ${SDC_CONF}/deployment-java-opts.txt ]]; then
       DEPLOYMENT_JAVA_OPTS=$(cat ${SDC_CONF}/deployment-java-opts.txt)
       if [[ ! -z ${DEPLOYMENT_JAVA_OPTS} ]]; then
@@ -396,10 +485,30 @@ run_bootstrap() {
 }
 
 run_sdc() {
+  reportEvent "INFO" "EXECUTION" "E01" "Starting engine"
   ${JAVA} -classpath ${BOOTSTRAP_CLASSPATH} ${SDC_JAVA_OPTS} com.streamsets.pipeline.BootstrapMain \
     -mainClass ${SDC_MAIN_CLASS} -apiClasspath "${API_CLASSPATH}" -containerClasspath "${CONTAINER_CLASSPATH}" \
     -streamsetsLibrariesDir "${STREAMSETS_LIBRARIES_DIR}" -userLibrariesDir "${USER_LIBRARIES_DIR}" -configDir ${SDC_CONF} \
-    -libsCommonLibDir "${LIBS_COMMON_LIB_DIR}" ${EXTRA_OPTIONS}
+    -libsCommonLibDir "${LIBS_COMMON_LIB_DIR}" ${EXTRA_OPTIONS} 2>&1 | tee /tmp/engine-$$.out
+  RET=$?
+  OUT=$(tail -50 /tmp/engine-$$.out)
+
+  # Remove credential cache if exists
+  #
+  if [ -f ${SDC_DATA}/sdc-krb5.ticketCache ]; then
+    rm ${SDC_DATA}/sdc-krb5.ticketCache
+  fi
+
+  if [[ ${RET} -eq 0 ]]; then
+    reportEvent "INFO" "EXECUTION" "E02" "Engine shutdown"
+    exit ${RET}
+  elif [[ ${RET} -eq 88 ]]; then
+    reportEvent "INFO" "EXECUTION" "E03" "Restarting Engine"
+  else
+    reportEvent "ERROR" "EXECUTION" "E04" "Exit: ${RET} STDOUT: ${OUT}"
+    echo "Exit: ${RET}"
+    exit ${RET}
+  fi
 }
 
 # we may need to exec the process in some cases. This is determined by option "-exec"
@@ -413,18 +522,11 @@ if [ $EXEC -eq 1 ]; then
 
   status=$?
 else
-  status=88
-  while [ $status = 88 ]; do
-    run_bootstrap && run_sdc
-    status=$?
+  while true; do
+    if [[ ${DEPLOYMENT_RUN} -eq 1 ]]; then
+      run_bootstrap
+    fi
+    run_sdc
+    status=${RET}
   done
 fi
-
-# Remove credential cache if exists
-#
-if [ -f ${SDC_DATA}/sdc-krb5.ticketCache ]; then
-  rm ${SDC_DATA}/sdc-krb5.ticketCache
-fi
-
-echo "Exit: $status"
-exit $status
